### ISSUE TITLE
Ability to have the app show zero on startup instead of last used values?

### ISSUE THREAD

**Issue by rodpolako** [SubhadeepJasu/pebbles#104]
Sorry if this is a really basic question but I'm not seeing how I can do this.

Is there a way to have the app start without the last actions still showing on the screen?

As an example, if I load the app and type 1+1 and hit enter, I get 2.  So far, so good.  If I close the app and then relaunch it I get the "1+1" showing as well as the result of "2".  I would like to have it start fresh with zeros instead of manually having to hit all-clear and enter or press the = button to reset.

Is there a setting or some other way to accomplish this?

**Comment by colinkiama** [comment]
Assign this issue to me please. I have a plan on how to solve this issue.
