### ISSUE TITLE
Save/restore settings across invocations

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#19]
The current calculator mode (scientific/calculus/converter etc.), the converter settings (convert from ... to ...), input field contents, etc. should be saved when the program is terminated and restored when it is restarted. (I remember reading this is a requirement for elementary apps somewhere in their UI guidelines.)

**Comment by SubhadeepJasu** [comment]
Auto restore previous view https://github.com/SubhadeepJasu/pebbles/commit/811c537bcdb312c67c4185b9df41933c2b8992d0

**Comment by SubhadeepJasu** [comment]
Save input and output states for scientific and calculus mode. https://github.com/SubhadeepJasu/pebbles/pull/32. More of these will be implemented soon.

**Comment by SubhadeepJasu** [comment]
https://github.com/SubhadeepJasu/pebbles/commit/a912f7543d03ccfd58426ba1e9c58dc27683e231

**Comment by SubhadeepJasu** [comment]
https://github.com/SubhadeepJasu/pebbles/commit/8f74273102448cee5d48e94bcfe5963a86a696de

**Comment by SubhadeepJasu** [comment]
https://github.com/SubhadeepJasu/pebbles/pull/43

**Comment by SubhadeepJasu** [comment]
I am gonna make a release soon. I'll close the issue, until we find other areas I might have missed. There were a ton of parameters to save.

**Comment by SubhadeepJasu** [comment]
https://github.com/SubhadeepJasu/pebbles/releases/tag/v1.0.3
