### ISSUE TITLE
Data conversion accuracy

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#20]
1 Kibibyte is 8191,995805698 bits? :)

![Screenshot from 2020-02-29 10-13-20](https://user-images.githubusercontent.com/25565229/75604730-221f4100-5adc-11ea-9da4-b8a2571dd81f.png)

**Comment by SubhadeepJasu** [comment]
Yeah the method it uses for conversion can cause inaccuracy. Should I remove decimal places entirely and round it off? As usual I need some advice on this.

**Comment by SubhadeepJasu** [comment]
Currently the accuracy is also tied to the "Number of decimal places" value in the settings.

**Comment by SubhadeepJasu** [comment]
For conversion to bits I will have to implement something like round off completely because its the smallest unit. I have to check this for all other converters too for which the smallest unit cannot further be broken down.

**Comment by SubhadeepJasu** [comment]
Fixed: https://github.com/SubhadeepJasu/pebbles/tree/f5ae3b2bfda434277bc14176556a1324a7bab950

**Comment by SubhadeepJasu** [comment]
Fixed and merged
