### ISSUE TITLE
GRD vs. GRA

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#21]
The button says GRD (for grad mode) but the LCD says GRA.

![Screenshot from 2020-02-29 10-13-56](https://user-images.githubusercontent.com/25565229/75604742-49760e00-5adc-11ea-97e9-675666917272.png)

Apologies for reporting minor nitpicking. Really love your app, it's beautiful and useful. Keep up the good work and don't forget that complaints are loud but praise is silent, so don't get frustrated by bug reports, they just show you that people use your app and care enough about it to take the time to submit the bug report in the first place.

**Comment by SubhadeepJasu** [comment]
Consider it done.

**Comment by SubhadeepJasu** [comment]
Fixed. Will close the issue when the next updates goes online.

**Comment by SubhadeepJasu** [comment]
@wolframroesler Don't worry. All feedback is appreciated and I'll work on them as soon as possible.
