### ISSUE TITLE
Large gray space around calculator

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#22]
Compared to the screenshots in App Center, I have a large gray space around the calculator.

![Screenshot from 2020-02-29 10-13-56](https://user-images.githubusercontent.com/25565229/75604797-ecc72300-5adc-11ea-92b0-21c2d5e23ef8.png)

About my machine:

![Screenshot from 2020-02-29 10-20-04](https://user-images.githubusercontent.com/25565229/75604818-197b3a80-5add-11ea-8139-f5c37e2eaa3f.png)

**Comment by SubhadeepJasu** [comment]
I need to confirm that it looks okay for the elementary theme at least for multiple resolutions. The app wasn't designed to scale. I might make things more dynamically scaling later with the addition of libhandy.

**Comment by NathanBnm** [comment]
Same issue here. It appeared after French translation being released:
![image](https://user-images.githubusercontent.com/45366162/79018164-6ab62980-7b73-11ea-8726-7144ec508641.png)

**Comment by SubhadeepJasu** [comment]
#78  most likely fixes this. Feel free to let me know if it doesn't.
