### ISSUE TITLE
Add "programmer" mode

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#23]
Suggesting to add a calculator mode for programmers, with hex input keys, hex/decimal/octal/binary display, not/and/or/xor operations, and integer/double/2-complement conversions. How about ASCII/Unicode display or UTF-8/16/32 conversion?

**Comment by SubhadeepJasu** [comment]
In the works

**Comment by SubhadeepJasu** [comment]
#73 . Will close when its merged.
