### ISSUE TITLE
Portuguese language

### ISSUE THREAD

**Issue by Ml12Cruz** [SubhadeepJasu/pebbles#29]
Por favor, traduza para uma versão em português também, se você poder, desde já agradeço, obrigado pelo seu trabalho. Não sei falar inglês. Please translate to a version in Portuguese too, if you can, from now on thank you, thank you for your work. I can't speak English.

**Comment by SubhadeepJasu** [comment]
Sure, localization is enabled. Anyone is free to translate it to their language. I don't know portuguese myself, but I am sure someone knows.

**Comment by xfgusta** [comment]
Olá, @Ml12Cruz. Traduzirei o Pebbles para o português brasileiro. Acredito que o gettext, a ferramenta que gerencia as traduções, permite também exibir as strings traduzidas para pt-BR para os falantes de português (pt), quando não existir tradução para pt.

Hey @SubhadeepJasu. I am planning to package Pebbles for Fedora Linux as well.

**Comment by SubhadeepJasu** [comment]
@xfgusta Obrigado! Isso é uma chatice se gettext não oferece suporte ao idioma português. Mas direi, devemos tentar o que podemos fazer. Ficarei feliz em ter sua ajuda.

Além disso, sobre portar o Pebbles para outras plataformas, claro que sim! (Embora eu não saiba o que precisa ser feito para mantê-lo nessas plataformas).
