### ISSUE TITLE
Add Travis CI

### ISSUE THREAD

**Issue by NathanBnm** [SubhadeepJasu/pebbles#31]
You have to register in Travis CI too if you want to use Continuous Integration (highly recommended). See the wiki here https://github.com/elementary/houston/wiki/Continuous-Integration.

**Comment by NathanBnm** [comment]
Edit: You have to change the node version from `lts/*` to `10.17.0` in order to make it work (see elementary/houston#773 for further info)

**Comment by SubhadeepJasu** [comment]
Thanks I will definitely look into it, although I need to learn about it a bit.

**Comment by SubhadeepJasu** [comment]
Ok, so currently receiving this error: `com.github.subhadeepjasu.pebbles.desktop: error: value "calculatrice;scientifique;programmeur;statistiques;convertisseur;convertir;calculer;bool?en; " for locale string list key "Keywords[fr]" in group "Desktop Entry" does not have a semicolon (';') as trailing character`, in the CI pipeline.

**Comment by NathanBnm** [comment]
All my fault, I accidentally added an extra space. #42 should fix this. (That's also why Travis CI is useful, I would have seen it if it was set before :smile:)

**Comment by SubhadeepJasu** [comment]
Yeah, I see now. Thanks again dude.

**Comment by NathanBnm** [comment]
The build just passed so I'm closing this!

**Comment by SubhadeepJasu** [comment]
Yeah, thanks.
