### ISSUE TITLE
Make escape key closing the controls window

### ISSUE THREAD

**Issue by NathanBnm** [SubhadeepJasu/pebbles#33]
Would be great to add this shortcut. The escape key is just near the F1 key.

**Comment by SubhadeepJasu** [comment]
ok

**Comment by SubhadeepJasu** [comment]
Might need some help. The preference window is no longer working if, I close it with escape key. I'll have to investigate whats going on with it. The controls modal works as expected. 

https://github.com/SubhadeepJasu/pebbles/commit/2c7f97fa25388c1765e88a7bafa428053a77fba0

**Comment by SubhadeepJasu** [comment]
Fixed
