### ISSUE TITLE
Comma not accepted as decimal separator

### ISSUE THREAD

**Issue by wolframroesler** [SubhadeepJasu/pebbles#45]
My machine is set to format numbers in the German way, which means decimal comma. Yet, Pebbles won't accept the comma key as a decimal separator but insists on a dot, which is bad because (1) there's a comma on my keyboard's num block, no dot, and (2) German formatting uses the dot as a thousands separator, making input like "123.456" ambiguous.

My language setting:

![Screenshot from 2020-03-29 00 22 07](https://user-images.githubusercontent.com/25565229/77836197-5d9d4180-7154-11ea-83e1-f851e86e09a4.png)

**Comment by SubhadeepJasu** [comment]
Wait, so in German localization, comma is actually decimal and dot is a separator?

**Comment by SubhadeepJasu** [comment]
https://github.com/SubhadeepJasu/pebbles/issues/44

**Comment by wolframroesler** [comment]
> Wait, so in German localization, comma is actually decimal and dot is a separator?

Yes, it's exactly the opposite as in English. Pi is 3,1415 and the number of millimeters in a kilometer is 1.000.000 -- and there's a comma key on the numpad.
