### ISSUE TITLE
Incorrect Behaviour When Using Brackets. Not Follow BODMAS Rules

### ISSUE THREAD

**Issue by DevendraAgarwal** [SubhadeepJasu/pebbles#47]
![Screenshot from 2020-04-09 11-26-38](https://user-images.githubusercontent.com/19260028/78864097-985a8000-7a58-11ea-851b-d8617008043e.png)
![Screenshot from 2020-04-09 11-27-06](https://user-images.githubusercontent.com/19260028/78864102-9a244380-7a58-11ea-8ba0-5db96e08c2ec.png)
![Screenshot from 2020-04-09 11-34-23](https://user-images.githubusercontent.com/19260028/78864104-9b557080-7a58-11ea-8804-b17f9d0c3828.png)

Please Fix This Issue. I think in 6/2(2+1) it is not considered 6 and just looks at 2(2+1) as 2/(2+1). OR Something Else, Please Fix it.

**Comment by SubhadeepJasu** [comment]
I have to add a system to consider any expression with consecutive a bracket and any operand to be considered as multiplication. Surely will do.

**Comment by SubhadeepJasu** [comment]
BTW It was designed to follow [PEMDAS](https://mathworld.wolfram.com/PEMDAS.html) rule instead of BODMAS or BEDMAS. The parenthesis issue can be fixed.

**Comment by SubhadeepJasu** [comment]
Done

**Comment by SubhadeepJasu** [comment]
Sorry, I previously got PEMDAS rule wrong. Its now fixed. Thank you.
