### ISSUE TITLE
Alignment issue on constant selection

### ISSUE THREAD

**Issue by NathanBnm** [SubhadeepJasu/pebbles#49]
There is an alignment issue on the constant selectors:

![image](https://user-images.githubusercontent.com/45366162/79018555-5aeb1500-7b74-11ea-8160-08e42db47053.png)

Using spaces between constant description and constant symbol is bad because it depends of the locale settings.

**Comment by SubhadeepJasu** [comment]
Yeah, is there a way to do it better or should we change it to just `<Constant Name> (<Constant symbol>)`?

**Comment by NathanBnm** [comment]
> Yeah, is there a way to do it better or should we change it to just `<Constant Name> (<Constant symbol>)`? There by not having to worry about aligning the symbols to the right.

I don't really know if there is a way to do better. Maybe it is possible to manage alignment in select input? I don't think so.

But for example with the `phi` or `lambda` constant this will give something like `<Constant Name> (<Phonetic name>) (<Constant symbol>)` which is bad because there are too much parenthesis.

**Comment by SubhadeepJasu** [comment]
I'll see is using a huge amount of space in the middle fixes it. I remember that being a thing.

**Comment by SubhadeepJasu** [comment]
I have modified it such that its all left aligned and the symbol appears inside " ". Is that okay? @NathanBnm

**Comment by SubhadeepJasu** [comment]
Closing for now as all of them are left aligned now. [v1.0.4](https://github.com/SubhadeepJasu/pebbles/releases/tag/v1.0.4)
