### ISSUE TITLE
🐞: Multiple errors in data convertion

### ISSUE THREAD

**Issue by joe733** [SubhadeepJasu/pebbles#50]
1MB = 512b = 512Mb?  😁

Multiple errors are seen across the data converter:

![image](https://user-images.githubusercontent.com/38415384/79075223-2069af80-7d0f-11ea-89de-f15e2ddd9479.png)
![Screenshot from 2020-04-12 22-41-56](https://user-images.githubusercontent.com/38415384/79075233-34adac80-7d0f-11ea-8e96-63e376e15fd9.png)

**Comment by SubhadeepJasu** [comment]
Fix is on the way. And holy ****, it was long overdue.

**Comment by SubhadeepJasu** [comment]
Fixed!
