### ISSUE TITLE
💡: Movable pointer text cursor in the input field

### ISSUE THREAD

**Issue by joe733** [SubhadeepJasu/pebbles#51]
Currently the text is editable from any position.
![Screenshot from 2020-04-12 22-50-49](https://user-images.githubusercontent.com/38415384/79075377-1a280300-7d10-11ea-808d-0c0cc1bcdbf1.png)

But blinking cursor won't budge using keyboard arrow keys <kbd>←</kbd> <kbd>→</kbd>

**Comment by SubhadeepJasu** [comment]
Fix underway: 60f50cdaa17ebfe756fe6bcd6beabe4acceec0f7
