### ISSUE TITLE
🐞: Blue bar appears when F8 is pressed

### ISSUE THREAD

**Issue by joe733** [SubhadeepJasu/pebbles#53]
I think `F8` is used to switch between the angles. But when I toggled `F8` in the `Date View` a blue line as seen in the picture gets toggled.

![image](https://user-images.githubusercontent.com/38415384/79189299-0333fe80-7e3f-11ea-8629-b12751e1f719.png)

**Comment by SubhadeepJasu** [comment]
Yup, saw that, but no idea what causes that. I'll ask some people.

**Comment by SubhadeepJasu** [comment]
The visual bug doesn't appear anymore for me, it may have been patched up stream. I am closing the issue, until it reappears.
