### ISSUE TITLE
Square of a value may output negative numbers...

### ISSUE THREAD

**Issue by jgomer2001** [SubhadeepJasu/pebbles#55]
I tried the following in pebbles (using Elementary os 5.1.4):

`1- 5/4`, press enter
Click AC (clear)
Click Ans and then Square (`x^2`), press enter

Result is `-.00625`. Result should be positive, ie. ` (-.25) x (-.25)`

I really like pebbles and have expectations around the upcoming programmer mode. But I'm a bit hesitant to use it as my everyday calculator due to small errors like the above.

Btw, is there a way to copy Ans to clipboard? or copy clipboard contents to the input?

**Comment by SubhadeepJasu** [comment]
There is a system for clipboard in it. I'll add the functionality back in. As for the error. I'll see to it.

**Comment by SubhadeepJasu** [comment]
Update, on doing a quick check ,it looks like it solves the exponent part first and then goes for the minus. The result is correct when I put (-0.25) in a bracket. I'll fiddle around with the precedence of that minus.

**Comment by SubhadeepJasu** [comment]
Fix is being worked upon: b863a771bb42fd036689a67f8f48d36f7330e06d . Someone can test if it works.
