### ISSUE TITLE
comma problem

### ISSUE THREAD

**Issue by awkse** [SubhadeepJasu/pebbles#57]
![Capture d'écran du 2020-05-19 16 21 32](https://user-images.githubusercontent.com/65608527/82338489-3db82a80-99ed-11ea-9719-adffb3310caa.png)

**Comment by SubhadeepJasu** [comment]
A fix is under way https://github.com/SubhadeepJasu/pebbles/commit/f36a7c9c1cf26b759fa040597b1268c130a24ec7 . I would need help in testing if it actually works. Right now the change is done in Scientific mode only. @NathanBnm ?? Anyone with that localization can test it, pls.

**Comment by NathanBnm** [comment]
@SubhadeepJasu I will be able to test tonight but not before

**Comment by SubhadeepJasu** [comment]
#44 #45 are related issues.

**Comment by NathanBnm** [comment]
@SubhadeepJasu I just tested and I have the same issue. I'll try to test with your fix.

**Comment by NathanBnm** [comment]
@SubhadeepJasu seems to be fixed on my side with French translation :+1:

**Comment by SubhadeepJasu** [comment]
Cool! I'll do the same for the entire application.

**Comment by SubhadeepJasu** [comment]
I just applied the fix for the entire application. I'll need to do some testing. We also need to test from other regions and languages. If everything works fine, I'll close this issue.

**Comment by NathanBnm** [comment]
> I just applied the fix for the entire application. I'll need to do some testing. We also need to test from other regions and languages. If everything works fine, I'll close this issue.

I'll try when I will have time

**Comment by SubhadeepJasu** [comment]
#58
