### ISSUE TITLE
pb of result

### ISSUE THREAD

**Issue by awkse** [SubhadeepJasu/pebbles#58]
![Capture d'écran du 2020-05-31 14 44 46](https://user-images.githubusercontent.com/65608527/83352691-b607df80-a34d-11ea-8be2-70e8e9cc2c7e.png)
I have download the new version on git  and compile it but the result of the operation is not correct.

**Comment by SubhadeepJasu** [comment]
May I know the localisation settings you are using? I mean the language settings.

**Comment by awkse** [comment]
I use elementary 5.1x in french localization, yesterday i have downloaded on git the last version, installed the libraries to compile it  and i use it like this  : com.github.subhadeepjasu.pebbles

**Comment by SubhadeepJasu** [comment]
I need to know if you switched branch before compiling.

**Comment by awkse** [comment]
hi, it's good, i have compiled it with the good branch : remediation.
 Thanks you.

**Comment by SubhadeepJasu** [comment]
Okay, cool! I'll merge and close the issue then.

**Comment by SubhadeepJasu** [comment]
Closing for now, will reopen if any issues pops up.
