### ISSUE TITLE
Use more natural left-to-right evaluation

### ISSUE THREAD

**Issue by jgomer2001** [SubhadeepJasu/pebbles#60]
In other calculators (even physical ones), typing `2/3*4` equals 2.666...

In pebbles, it turns out to be 0.6666... i.e. 2/(3*4) 

Personally I don't like the idea of introducing parenthesis for pebbles to get it right. I think not using the standard behavior (L to R) for operands with the same priority is undesirable

**Comment by SubhadeepJasu** [comment]
Okay, then I'll include an option to switch between PEMDAS and BODMAS.

**Comment by SubhadeepJasu** [comment]
Done
