### ISSUE TITLE
Offer this app through Flathub?

### ISSUE THREAD

**Issue by felipehw** [SubhadeepJasu/pebbles#66]
Hi. I tried to search how to install this app in a non-eOS but I didn't find a channel.
Maybe a good idea to offer this app through Flathub?

**Comment by SubhadeepJasu** [comment]
Yeah, we do plan to do it.

**Comment by felipehw** [comment]
@SubhadeepJasu 
Thanks!

**Comment by SubhadeepJasu** [comment]
Thanks to @danilown :smile:
