### ISSUE TITLE
Combinations

### ISSUE THREAD

**Issue by yurutken** [SubhadeepJasu/pebbles#69]
14C5 equals to 2002
Pebbles doesn't agree that ! :)
Maybe i made something wrong ? Relatively small combination calculations are correct

**Comment by yurutken** [comment]
![Screenshot from 2021-01-06 23-52-47](https://user-images.githubusercontent.com/12844199/103818922-79862a00-507a-11eb-81ae-41f47fb5f07d.png)

**Comment by SubhadeepJasu** [comment]
Okay, I will look into it.

**Comment by SubhadeepJasu** [comment]
Fixed in commit c002aa7
