### ISSUE TITLE
wrong number

### ISSUE THREAD

**Issue by gigi55** [SubhadeepJasu/pebbles#72]
![Capture d'écran du 2021-02-07 12 24 26y](https://user-images.githubusercontent.com/8693514/107145465-e888c400-6941-11eb-8b2f-a6d66b466eac.png)
 in "smaller mode" zero number is absent

**Comment by SubhadeepJasu** [comment]
Fixed. I will close the issue when I merge it to master :+1:

**Comment by gigi55** [comment]
great job. i appreciate  👌️
