### ISSUE TITLE
Change required for AppCenter: Accurate OARS data

### ISSUE THREAD

**Issue by cassidyjames** [SubhadeepJasu/pebbles#75]
Thanks for submitting your 1.1.0 update to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

As listed in the AppCenter Publishing Requirements, [you must include accurate OARS data](https://docs.elementary.io/develop/appcenter/publishing-requirements#appdata-and-oars) in your AppData. Since your app uses an external web service, its `social-info` value **must** be set to `mild` or higher, depending on the data that is sent. You can always ensure your OARS data is correct by using the [official OARS generator](https://hughsie.github.io/oars/).

https://github.com/SubhadeepJasu/pebbles/blob/410cc869c8e8dff3641c8617dd97509dc380fc04/src/Core/CurrencyConverter.vala#L94

https://github.com/SubhadeepJasu/pebbles/blob/410cc869c8e8dff3641c8617dd97509dc380fc04/data/com.github.subhadeepjasu.pebbles.appdata.xml.in#L1-L154

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by SubhadeepJasu** [comment]
Gotcha 👍

**Comment by SubhadeepJasu** [comment]
Fixed
