### ISSUE TITLE
Unclear how to define upper and lower limits for integrals

### ISSUE THREAD

**Issue by johnblommers** [SubhadeepJasu/pebbles#76]
It's unclear how to define the upper and lower limits of integration. Could you provide a detailed example of how that's done. The tooltip tells about it but there is no UI to set these values.

**Comment by SubhadeepJasu** [comment]
Sorry for the inconvenience. Here's the layout:
![Layout](https://user-images.githubusercontent.com/20795161/118934263-cbfc1f00-b967-11eb-9b30-f91dadcad2ca.png)

**Comment by SubhadeepJasu** [comment]
![Screenshot from 2021-05-20 12-36-04](https://user-images.githubusercontent.com/20795161/118934465-04036200-b968-11eb-81d7-9b0ee30bbede.png)

So you write an expression in the main input. You can use _x_ button to insert a variable. You can then enter the limits and press the ∫ button to evaluate the expression.

**Comment by SubhadeepJasu** [comment]
Update: I'll try redesigning that area a bit, so that its more clear.

**Comment by johnblommers** [comment]
Aha I see it now. My difficulties were because:

1. I did not understand why there were two multiplication buttons. There aren't. One means multiply, the other means symbolic X.
1. The limits buttons are not labeled as such.
1. I was trying to integrate sinx/x between 0 and 1 but sinx/x  is 0/0 at x=0 and Pebbles does not like that, displaying an E for error.
1. I was trying to integrate between -1 and +1 but there is no way to type in a negative limit of integration. Or to type a decimal quantity. Only integers are accepted. Pressing the decimal doesn't appear to register. So you cannot type in 0.000001 either.

**Comment by SubhadeepJasu** [comment]
I see. It's a good catch. Also, pressing decimal does register. You have to click the textbox once to get that into focus. You can also use the on-screen keypad button on the side of those textboxes.

**Comment by SubhadeepJasu** [comment]
Added a way to tweak Simpson's algorithm accuracy: And it now prevents a divide by zero error in integral calculus mode, by replacing it with the smallest double value supported.

![image](https://user-images.githubusercontent.com/20795161/119138507-963a6180-ba5f-11eb-99a2-4e2046eb3f09.png)

I'll add some icons and stuff to make using and discovering the ui stuff in calculus mode much easier.

**Comment by johnblommers** [comment]
I'm looking forward to "kicking the tires" of your next release :-)

**Comment by SubhadeepJasu** [comment]
I am glad you pointed these out.

**Comment by johnblommers** [comment]
It's fun to try out innovative calculator applications. 

Developers need testers, writers need beta readers and presenters need practice sessions.

**Comment by SubhadeepJasu** [comment]
Thanks to you, calculus mode got a bit better now. 
![image](https://user-images.githubusercontent.com/20795161/119838750-448f4c80-bf21-11eb-8150-d4697122e2ae.png)

**Comment by johnblommers** [comment]
&check;

**Comment by SubhadeepJasu** [comment]
Its from odin-ui-changes branch. Plus, I am using a Odin theme on Hera.

**Comment by SubhadeepJasu** [comment]
#78 implements these fixes and improvements. Closing. Have a nice day :). Let me know if I missed anything.
